#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define LEVEL_WIDTH 1280
#define LEVEL_HEIGHT 960

#define FPS 60
#define FRAME_DELAY (1000 / FPS)

#define TILE_SIZE 1

#define MOV_SPEED 1
#define ROTATION_SPEED 0.01

#endif // CONSTANTS_H